### ISSUE TITLE
Not able to retrieve get-logins

### ISSUE THREAD

**Issue by dimon222** [hrehfeld/python-keepassxc-browser#13]
Currently script works with saving logins, but not retrieving them.
Not sure if it's anyhow related to encryption message mechanic. Essentially, it gives back "No logins found"
I pass matching URL. I tried to include submitURL too, but it still says no logins found.

Platform: Darwin
Python 3.7.5
Installed github version using setup.py

**Comment by varjolintu** [comment]
If you are using KeePassXC 2.5.1 try to downgrade to 2.5.0 or try the snapshot build while waiting for 2.5.2. The matching had some bugs that are already fixed.

**Comment by hrehfeld** [comment]
Can you confirm that 2.5.1 is broken?

**Comment by varjolintu** [comment]
There's the fix for 2.5.2: https://github.com/keepassxreboot/keepassxc/pull/3854

**Comment by omgold** [comment]
I can confirm the issue.

To me it was introduced exactly at version 2.5.0, and it is still present at current release/2.5.2 (0fd883686c05c7689bf8f074b02dcfff3a705a97).

The plugins for neither Firefox nor Chrome show any problems, though.

**Comment by dimon222** [comment]
2.5.2 is out, issue is still happening in this python module. Always not found.

**Comment by Heiko-san** [comment]
I can confirm the issue with keepassxc 2.4.3 (ubuntu 19.10 repo version).
Same for 2.5.2 (ppa version).
Is there any way to fix it ?
Password creation works but I need the get-logins function.
Browser Plugin (chrome & firefox) is working.

I have the 2 options active to match the URL-Scheme and only return best matches. However it doesn't change anything to disable them.

The message sent however seems to be ok:
```
{'action': 'get-logins', 'triggerUnlock': 'true', 'url': 'https://python-test123', 'keys': [{'key': '...', 'idKey': '...'}]}
```
The only thing I find is that https://github.com/keepassxreboot/keepassxc-browser/blob/develop/keepassxc-protocol.md talks about "id" instead of "idKey". But since the error is not about permissions and I tried changing it to "id" (with no effect), I guess idKey is ok.

The full stacktrace is:
```
Traceback (most recent call last):
  File "./foo.py", line 42, in <module>
    main()
  File "./foo.py", line 36, in main
    c.get_logins(id, url='https://python-test123')
  File "/home/hfi/git/3rd_party/python-keepassxc-browser/keepassxc_browser/protocol.py", line 253, in get_logins
    resp_message = self.encrypt_message_send_command(identity, action, message)
  File "/home/hfi/git/3rd_party/python-keepassxc-browser/keepassxc_browser/protocol.py", line 179, in encrypt_message_send_command
    return self.send_encrypted_command(identity, command, nonce)
  File "/home/hfi/git/3rd_party/python-keepassxc-browser/keepassxc_browser/protocol.py", line 173, in send_encrypted_command
    resp = self.send_command(identity, command, nonce, next_nonce)
  File "/home/hfi/git/3rd_party/python-keepassxc-browser/keepassxc_browser/protocol.py", line 167, in send_command
    raise ProtocolError(resp['error'])
keepassxc_browser.exceptions.ProtocolError: Keine Anmeldedaten gefunden
```
maybe this helps somehow
The code is the example with just the 2 creation lines commented out (entry was created in an earlier run and I tried with other entries too) and another client_id.

**Comment by Phidica** [comment]
@varjolintu you seem to be the only author of the keepassxc-protocol document mentioned above. It doesn't show any changes happening in the protocol for a long time. Is that correct? Is the protocol document fully up to date?

**Comment by varjolintu** [comment]
@Phidica It should be. I'll take a look at this issue today and try to find out what really happens.

**Comment by varjolintu** [comment]
https://github.com/hrehfeld/python-keepassxc-browser/pull/14 - here's the fix.
